#!/bin/bash -l

# Set SCC project
#$ -P infant-microbiome

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=10:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m ea

# Give job a name
#$ -N fastqc

# Request cores
#$ -pe omp 8

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o run_fastqc.qlog

# Ask for scratch space
#$ -l scratch=100G

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

#load packages
module load fastqc
echo ""

#run fastqc
fastqc /restricted/projectnb/infant-microbiome/data/death_sepsis_controls/*.fastq.gz -o /restricted/projectnb/infant-microbiome/work/aodom/Sepsis/control_fastqc_results

echo ""
echo "Analysis Complete!"
