#!/bin/bash -l

# Set SCC project
#$ -P johnsonlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=24:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N sepsis_blast_weissella

# Request eight cores
#$ -pe omp 8

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o blast_fasta_weissella.qlog

#   ask for scratch space
#$ -l scratch=100G

# Submit an array job with n tasks
#$ -t 1-2

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# Keep this location! BLAST database location!
cd /restricted/projectnb/pathoscope/data/blastdb/nt

### SETUP
dataDir=/restricted/projectnb/infant-microbiome/work/aodom/Sepsis/run_metascope/metascope_out
fastaDir=$dataDir/blast_fastas
inputs=(${fastaDir}/X3333_Weissella_*.fasta) # FIX THIS
index=$(($SGE_TASK_ID-1))
fastafile=${inputs[$index]##*/}
sampleName=${fastafile%%.fasta}

echo $sampleName

module load blast+

blastn -query $fastaDir/$fastafile -db nt -out $fastaDir/${sampleName}_ntBlastResults.csv -outfmt "10 qseqid sacc sscinames score evalue"